package example.swing.components;

import example.engine.PlayersManager;
import example.swing.components.init.PlayersManagerPanel;
import java.awt.CardLayout;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import javax.swing.JFrame;

public class PlayersManagerFrame extends JFrame {
    private PlayersManager playersManager;

    /**
     * Creates new form PlayerManagerFrame
     */
    public PlayersManagerFrame() {
	playersManager = new PlayersManager();
	initComponents();
	setLocationRelativeTo(null);
	playersManagerPanel.setPlayersManager(playersManager);
	((CardLayout)getContentPane().getLayout()).show(getContentPane(), "initPanel");
	initListeners();

    }

    private void initListeners(){
	playersManagerPanel.addPropertyChangeListener(PlayersManagerPanel.FINISHED_INIT_EVENT, new PropertyChangeListener() {
	    @Override
	    public void propertyChange(PropertyChangeEvent evt) {
		showBoardPanel();
	    }
	});
    }

    private void showBoardPanel() {
	boardPanel.setPlayers(playersManager.getPlayers());
	((CardLayout)getContentPane().getLayout()).show(getContentPane(), "boardPanel");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playersManagerPanel = new example.swing.components.init.PlayersManagerPanel();
        boardPanel = new example.swing.components.main.BoardPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Players Manager");
        setPreferredSize(new java.awt.Dimension(398, 300));
        getContentPane().setLayout(new java.awt.CardLayout());
        getContentPane().add(playersManagerPanel, "initPanel");
        getContentPane().add(boardPanel, "boardPanel");

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private example.swing.components.main.BoardPanel boardPanel;
    private example.swing.components.init.PlayersManagerPanel playersManagerPanel;
    // End of variables declaration//GEN-END:variables
}
