package example.swing.components.init.playerslist;

import example.engine.model.Player;
import java.awt.Dimension;
import javax.swing.BorderFactory;

/**
 *
 * @author Iblecher
 */
public class PlayersListPanel extends javax.swing.JPanel {

    /**
     * Creates new form PlayersListPanel
     */
    public PlayersListPanel() {
	initComponents();
    }

    public void addPlayer (Player player){
	add(new PlayerPanel(player.getName()));
	this.validate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(BorderFactory.createTitledBorder("Players List"));
        setMinimumSize(new Dimension(22, 400));
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
