package example.swing.components.init;

import example.engine.PlayersManager;
import example.engine.exceptions.DuplicateNameException;
import example.engine.model.Player;
import example.swing.components.init.addplayer.AddPlayerPanel;
import example.swing.components.init.playerslist.PlayersListPanel;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author Iblecher
 */
public class PlayersManagerPanel extends javax.swing.JPanel {

    public static final String FINISHED_INIT_EVENT = "finishedInitEvent";

    private PlayersManager playersManager;

    /**
     * Creates new form PlayersManagerPanel
     */
    public PlayersManagerPanel() {
	initComponents();
	initAddPlayerPanelListener();
    }

    public void setPlayersManager(PlayersManager playersManager) {
	this.playersManager = playersManager;
    }

    private void initAddPlayerPanelListener() {
	addPlayerPanel.addPropertyChangeListener(AddPlayerPanel.PLAYER_ADD_EVENT, new PropertyChangeListener() {
	    @Override
	    public void propertyChange(PropertyChangeEvent evt) {
		addPlayer();
	    }
	});
    }

    private void addPlayer() {
	String playerName = addPlayerPanel.getPlayerName();
	try {
	    Player player = playersManager.addPlayer(playerName);
	    playersListPanel.addPlayer(player);
	    addPlayerPanel.clear();
	} catch (DuplicateNameException duplicateNameException){
	    addPlayerPanel.showErrorMessage(duplicateNameException.getMessage());
	}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playersListPanel = new PlayersListPanel();
        mainButtonsPanel = new JPanel();
        continueButton = new JButton();
        addPlayerPanel = new AddPlayerPanel();

        setMinimumSize(new Dimension(185, 300));
        setLayout(new BorderLayout());
        add(playersListPanel, BorderLayout.CENTER);

        continueButton.setText("Continue");
        continueButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                continueButtonActionPerformed(evt);
            }
        });

        GroupLayout mainButtonsPanelLayout = new GroupLayout(mainButtonsPanel);
        mainButtonsPanel.setLayout(mainButtonsPanelLayout);
        mainButtonsPanelLayout.setHorizontalGroup(
            mainButtonsPanelLayout.createParallelGroup(Alignment.LEADING)
            .addGroup(Alignment.TRAILING, mainButtonsPanelLayout.createSequentialGroup()
                .addContainerGap(315, Short.MAX_VALUE)
                .addComponent(continueButton)
                .addContainerGap())
        );
        mainButtonsPanelLayout.setVerticalGroup(
            mainButtonsPanelLayout.createParallelGroup(Alignment.LEADING)
            .addGroup(Alignment.TRAILING, mainButtonsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(continueButton, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(mainButtonsPanel, BorderLayout.PAGE_END);
        add(addPlayerPanel, BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void continueButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_continueButtonActionPerformed
        firePropertyChange(FINISHED_INIT_EVENT, false, true);
    }//GEN-LAST:event_continueButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private AddPlayerPanel addPlayerPanel;
    private JButton continueButton;
    private JPanel mainButtonsPanel;
    private PlayersListPanel playersListPanel;
    // End of variables declaration//GEN-END:variables
}
