/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package swing.components.game;

import engine.Engine;
import engine.players.Player;
import javax.swing.JPanel;
import swing.components.game.play.JPanelHand;
import swing.components.game.play.playarea.PlayAreaFactory;

/**
 *
 * @author Natalie
 */
public class JPanelGame extends javax.swing.JPanel {

    private Engine engine;
    private swing.components.game.graveyard.JPanelGraveyard jPanelGraveyard;
    private swing.components.game.play.playarea.JPanelPlayAreaCards jPanelPlayAreaCards;
    private swing.components.game.playerlist.JPanelPlayerList jPanelPlayerList;

    /**
     * Creates new form JPanelGame
     */
    public JPanelGame() {
        initComponents();
        this.engine = null;
    }

    public void initGame(Engine engine) {
        this.engine = engine;
        initHandClass();
        initGraveyard();
        initPlayAreaCards();
        initPlayersList();
        revalidate();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        this.jPanelPlayerList = new swing.components.game.playerlist.JPanelPlayerList();
        this.jPanelPlayAreaCards = new swing.components.game.play.playarea.JPanelPlayAreaCards();
        this.jPanelGraveyard = new swing.components.game.graveyard.JPanelGraveyard();

        setLayout(new java.awt.BorderLayout());
        add(jPanelPlayerList, java.awt.BorderLayout.WEST);
        add(jPanelPlayAreaCards, java.awt.BorderLayout.CENTER);
        add(jPanelGraveyard, java.awt.BorderLayout.EAST);
    }

    private void initGraveyard() {
        this.jPanelGraveyard.setEngine(engine);
    }

    private void initPlayAreaCards() {
        for (Player player : this.engine.getPlayers()) {
            String playerName = player.getName();
            JPanel jPanelPlayArea = PlayAreaFactory.makeJPanelPlayArea(player);
            this.jPanelPlayAreaCards.addCard(jPanelPlayArea, playerName);
        }

        this.jPanelPlayAreaCards.showCard(engine.getCurrentPlayer().getName());
    }

    private void initPlayersList() {
        this.jPanelPlayerList.setEngine(engine);
    }

    private void initHandClass() {
        JPanelHand.setAvailableSeries(engine.getAvailableSeries());

    }
}
