/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package swing.components.game;

import engine.Engine;

/**
 *
 * @author Natalie
 */
public class JPanelGame extends javax.swing.JPanel {

    private Engine engine;
    
    /**
     * Creates new form JPanelGame
     */
    public JPanelGame() {
        initComponents();
        this.engine = null;
    }
    
    public void initGame(Engine engine){
        this.engine = engine;
        initGraveyard();
        initPlayAreaCards();
        initPlayersList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelGraveyard1 = new swing.components.game.graveyard.JPanelGraveyard();
        jPanelPlayerList1 = new swing.components.game.playerlist.JPanelPlayerList();
        jPanelPlayAreaCards1 = new swing.components.game.play.playarea.JPanelPlayAreaCards();

        setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanelGraveyard1Layout = new javax.swing.GroupLayout(jPanelGraveyard1);
        jPanelGraveyard1.setLayout(jPanelGraveyard1Layout);
        jPanelGraveyard1Layout.setHorizontalGroup(
            jPanelGraveyard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 88, Short.MAX_VALUE)
        );
        jPanelGraveyard1Layout.setVerticalGroup(
            jPanelGraveyard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        add(jPanelGraveyard1, java.awt.BorderLayout.LINE_END);

        javax.swing.GroupLayout jPanelPlayerList1Layout = new javax.swing.GroupLayout(jPanelPlayerList1);
        jPanelPlayerList1.setLayout(jPanelPlayerList1Layout);
        jPanelPlayerList1Layout.setHorizontalGroup(
            jPanelPlayerList1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 88, Short.MAX_VALUE)
        );
        jPanelPlayerList1Layout.setVerticalGroup(
            jPanelPlayerList1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        add(jPanelPlayerList1, java.awt.BorderLayout.LINE_START);
        add(jPanelPlayAreaCards1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.components.game.graveyard.JPanelGraveyard jPanelGraveyard1;
    private swing.components.game.play.playarea.JPanelPlayAreaCards jPanelPlayAreaCards1;
    private swing.components.game.playerlist.JPanelPlayerList jPanelPlayerList1;
    // End of variables declaration//GEN-END:variables

    private void initGraveyard() {
        this.jPanelGraveyard1.setEngine(engine);
    }

    private void initPlayAreaCards() {
        
    }

    private void initPlayersList() {
        this.jPanelPlayerList1.
    }
}
