/*
 */
package swing.components.game;

import engine.cards.Card;
import engine.cards.Series;
import java.util.LinkedList;

/**
 *
 * @author adamnark
 */
public class JPanelTest extends javax.swing.JPanel {

    /**
     * Creates new form JPanelTest
     */
    public JPanelTest() {
        initComponents();
        LinkedList<Series> series = makeSeries();
        LinkedList<Card> cards = makeCards(series);

        JButtonCard.setAvailableSeries(series);

        for (Card card : cards) {
            JButtonCard jPanelCard = new JButtonCard(card);
            this.add(jPanelCard);
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    private LinkedList<Series> makeSeries() {
        LinkedList<Series> series = new LinkedList<>();
        series.add(new Series("ting tong"));
        series.add(new Series("fing fong"));
        series.add(new Series("ling long"));
        series.add(new Series("ping pong"));
        series.add(new Series("shing shong"));
        series.add(new Series("zing zong"));
        
        return series;
    }

    private LinkedList<Card> makeCards(LinkedList<Series> series) {
        LinkedList<Card> cards = new LinkedList<>();
        
        for (int i = 0; i < series.size(); i+=2) {
            Series srs1 = series.get(i);
            Series srs2 = series.get(i+1);
            Card card = new Card();
            card.addSeries(srs1);
            card.addSeries(srs2);
            card.setName(srs1.getName());
            cards.add(card);
            
        }

        return cards;
    }
}
