/*
 */
package swing.components.settings.manual;

import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author adamnark
 */
public class JPanelAddPlayer extends javax.swing.JPanel {

    public static final String ADD_PLAYER_EVENT = "ADD_PLAYER_EVENT";

    /**
     * Creates new form JPanelAddPlayer
     */
    public JPanelAddPlayer() {
        initComponents();
        initTextFieldListeners();
        hideErrorMessage();
    }

    public void clear() {
        hideErrorMessage();
        this.jTextFieldPlayerName.setText("");
        this.jCheckBoxIsPlayerHuman.setSelected(false);
    }

    public String getPlayerName() {
        return this.jTextFieldPlayerName.getText();
    }
    
    public boolean isPlayerHuman(){
        return this.jCheckBoxIsPlayerHuman.isSelected();
    }

    private void fireAddPlayerEvent() {
        this.firePropertyChange(ADD_PLAYER_EVENT, true, false);
    }

    private void hideErrorMessage() {
        this.jLabelErrorMessage.setText("");
        this.jLabelErrorMessage.setVisible(false);
    }

    public void showErrorMessage(String errorMessage) {
        this.jLabelErrorMessage.setText(errorMessage);
        this.jLabelErrorMessage.setVisible(true);
    }

    private void updateButtonStatus() {
        this.jButtonAddPlayer.setEnabled(!this.jTextFieldPlayerName.getText().isEmpty());
    }

    private void initTextFieldListeners() {
        this.jTextFieldPlayerName.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent de) {
                updateButtonStatus();
            }

            @Override
            public void removeUpdate(DocumentEvent de) {
                updateButtonStatus();
            }

            @Override
            public void changedUpdate(DocumentEvent de) {
                updateButtonStatus();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPlayerName = new javax.swing.JLabel();
        jTextFieldPlayerName = new javax.swing.JTextField();
        jCheckBoxIsPlayerHuman = new javax.swing.JCheckBox();
        jButtonAddPlayer = new javax.swing.JButton();
        jLabelErrorMessage = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Add Player"));

        jLabelPlayerName.setText("Player Name:");

        jTextFieldPlayerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPlayerNameActionPerformed(evt);
            }
        });

        jCheckBoxIsPlayerHuman.setText("Human Player");

        jButtonAddPlayer.setText("Add Player");
        jButtonAddPlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddPlayerActionPerformed(evt);
            }
        });

        jLabelErrorMessage.setForeground(new java.awt.Color(255, 51, 51));
        jLabelErrorMessage.setText("ERROR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelPlayerName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPlayerName))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckBoxIsPlayerHuman)
                        .addGap(0, 127, Short.MAX_VALUE))
                    .addComponent(jLabelErrorMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAddPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPlayerName)
                    .addComponent(jTextFieldPlayerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxIsPlayerHuman)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAddPlayer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelErrorMessage))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddPlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddPlayerActionPerformed
        this.fireAddPlayerEvent();
    }//GEN-LAST:event_jButtonAddPlayerActionPerformed

    private void jTextFieldPlayerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPlayerNameActionPerformed
        this.fireAddPlayerEvent();
    }//GEN-LAST:event_jTextFieldPlayerNameActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddPlayer;
    private javax.swing.JCheckBox jCheckBoxIsPlayerHuman;
    private javax.swing.JLabel jLabelErrorMessage;
    private javax.swing.JLabel jLabelPlayerName;
    private javax.swing.JTextField jTextFieldPlayerName;
    // End of variables declaration//GEN-END:variables
}
