/*
 */
package swing.components.game.play;

import swing.components.game.card.JButtonCard;
import engine.cards.Card;
import engine.cards.Series;
import engine.players.Hand;
import java.util.LinkedList;
import java.util.List;

/**
 *
 * @author adam
 */
public class JPanelHand extends javax.swing.JPanel {

    private Hand handModel;
    private LinkedList<JButtonCard> jPanelButtonCardList;
    private static boolean isClassInitiated = false;

    /**
     * Creates new form JPanelHand
     */
    public JPanelHand() {
        if (!JPanelHand.isClassInitiated) {
            //throw new RuntimeException("Can't instantiate JPanelHand before calling setAvailableSeries()!");
        }

        this.jPanelButtonCardList = new LinkedList<>();
        this.handModel = null;
        initComponents();
    }

    public void setHandModel(Hand handModel) {
        this.handModel = handModel;
    }

    public void update() {
        if (this.handModel == null) {
            throw new RuntimeException("JPanelHand needs a hand model! please call setHandModel().");
        }

        for (JButtonCard jButtonCard : jPanelButtonCardList) {
            this.remove(jButtonCard);
        }

        this.addButtonsFromHandModel();
        this.revalidate();
        this.repaint();
    }

    private void addButtonsFromHandModel() {
        for (Card card : this.handModel.getCards()) {
            this.jPanelButtonCardList.add(new JButtonCard(card));
        }
    }

    public static void setAvailableSeries(List<Series> availableSeries) {
        JButtonCard.setAvailableSeries(availableSeries);
        JPanelHand.isClassInitiated = true;
    }

    public void setPlayerName(String name) {
        String title = name + "'s Hand";
        this.setBorder(javax.swing.BorderFactory.createTitledBorder(title));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(javax.swing.BorderFactory.createTitledBorder("Player's Hand"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
