/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package swing.components.game.play;

/**
 *
 * @author Natalie
 */
public class JPanelActions extends javax.swing.JPanel {

    /**
     * Creates new form JPanelActions
     */
    public JPanelActions() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("What do you want to do?"));

        jButton1.setText("Request");
        jButton1.setToolTipText("Request a card");
        jButton1.setPreferredSize(new java.awt.Dimension(100, 70));
        add(jButton1);

        jButton2.setText("Throw");
        jButton2.setToolTipText("Throw selected cards");
        jButton2.setPreferredSize(new java.awt.Dimension(100, 70));
        add(jButton2);

        jButton3.setText("Skip");
        jButton3.setToolTipText("Skip the rest of your turn");
        jButton3.setPreferredSize(new java.awt.Dimension(100, 70));
        add(jButton3);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    // End of variables declaration//GEN-END:variables
}
