package example;

import example.validation.Validatable;
import example.validation.Validator;
import java.awt.Color;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.*;

/**
 *
 * @author Liron Blecher
 */
public class PlayersDetailsPanel extends JPanel implements Validatable{
    private Validator validator;
    /**
     * Creates new form PlayersDetailsPanel
     */
    public PlayersDetailsPanel() {
        initComponents();
    }

    @Override
    public void beDisable() {
        humanTypeRadioButton.setEnabled(false);
        computerTypeRadioButton.setEnabled(false);
    }

    @Override
    public void beEnabled() {
        humanTypeRadioButton.setEnabled(true);
        computerTypeRadioButton.setEnabled(true);
    }

    @Override
    public String getPlayerName() {
        return playerNameTextField.getText();
    }

    @Override
    public boolean getPlayerType() {
        return humanTypeRadioButton.isSelected();
    }

  

    @Override
    public void setValidtor(Validator validator) {
        this.validator = validator;
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new ButtonGroup();
        jLabel1 = new JLabel();
        playerNameTextField = new JTextField();
        humanTypeRadioButton = new JRadioButton();
        computerTypeRadioButton = new JRadioButton();
        errorLabel = new JLabel();

        jLabel1.setText("Name:");

        playerNameTextField.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent evt) {
                playerNameTextFieldKeyTyped(evt);
            }
        });

        buttonGroup1.add(humanTypeRadioButton);
        humanTypeRadioButton.setSelected(true);
        humanTypeRadioButton.setText("Human");

        buttonGroup1.add(computerTypeRadioButton);
        computerTypeRadioButton.setText("Computer");

        errorLabel.setForeground(new Color(255, 51, 51));
        errorLabel.setHorizontalAlignment(SwingConstants.CENTER);

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(Alignment.LEADING)
                    .addComponent(playerNameTextField, GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                    .addComponent(errorLabel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(Alignment.LEADING, false)
                    .addComponent(humanTypeRadioButton)
                    .addComponent(computerTypeRadioButton))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(playerNameTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(humanTypeRadioButton))
                .addPreferredGap(ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(computerTypeRadioButton)
                        .addContainerGap())
                    .addGroup(Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(errorLabel))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void playerNameTextFieldKeyTyped(KeyEvent evt) {//GEN-FIRST:event_playerNameTextFieldKeyTyped
        if (this.validator != null) {
            this.validator.playerNameChanged(this);
        }
    }//GEN-LAST:event_playerNameTextFieldKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ButtonGroup buttonGroup1;
    private JRadioButton computerTypeRadioButton;
    private JLabel errorLabel;
    private JRadioButton humanTypeRadioButton;
    private JLabel jLabel1;
    private JTextField playerNameTextField;
    // End of variables declaration//GEN-END:variables
}
