/*
 */
package swing.playerinterface;

import engine.cards.Series;
import engine.players.Hand;
import engine.players.Player;
import java.awt.Color;
import java.util.LinkedList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JCheckBox;

/**
 *
 * @author adamnark
 */
public class JPanelRequest extends javax.swing.JPanel {

    private Hand hand;
    private List<Series> availableSeries;
    private List<Player> otherPlayers;
    private DefaultComboBoxModel otherPlayerComboBoxModel;
    private List<JCheckBox> jCheckBoxes;
    public static final String EVENT_DONE = "JPanelRequest - done";
    public static final String EVENT_CANCEL = "JPanelRequest - cancel";

    /**
     * Creates new form JPanelRequest
     */
    public JPanelRequest() {
        initComponents();
        jCheckBoxes = new LinkedList<>();
        clearErrorMessage();
    }

    public final void clearErrorMessage() {
        this.jLabelErrorMessage.setText("");
    }

    public void setErrorMessage(String message) {
        this.jLabelErrorMessage.setText(message);
        this.jLabelErrorMessage.setForeground(Color.red);
    }

    public void appendErrorMessage(String message) {
        String old = this.jLabelErrorMessage.getText();
        setErrorMessage(old + "\n" + message);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxOtherPlayers = new javax.swing.JComboBox();
        jPanelSeries = new javax.swing.JPanel();
        jButtonOk = new javax.swing.JButton();
        jLabelErrorMessage = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(400, 400));
        setMinimumSize(new java.awt.Dimension(400, 400));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Make a Request");

        jLabel2.setText("Pick a player:");

        jPanelSeries.setBorder(javax.swing.BorderFactory.createTitledBorder("Pick series"));
        jPanelSeries.setMaximumSize(new java.awt.Dimension(380, 200));
        jPanelSeries.setMinimumSize(new java.awt.Dimension(380, 30));

        jButtonOk.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonOk.setText("Request!");
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });

        jLabelErrorMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelErrorMessage.setText("ERRORS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jButtonOk))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxOtherPlayers, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelSeries, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelErrorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxOtherPlayers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanelSeries, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelErrorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonOk)
                .addGap(28, 28, 28))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
        clearErrorMessage();
        boolean isValid = validateRequest();
        if (isValid) {
            firePropertyChange(EVENT_DONE, false, true);
        }
    }//GEN-LAST:event_jButtonOkActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOk;
    private javax.swing.JComboBox jComboBoxOtherPlayers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelErrorMessage;
    private javax.swing.JPanel jPanelSeries;
    // End of variables declaration//GEN-END:variables

    public void setHand(Hand hand) {
        this.hand = hand;
    }

    public void setAvailableSeries(List<Series> availableSeries) {
        this.availableSeries = availableSeries;
        initJPanelSeries();
    }

    public void setListOfPlayers(List<Player> otherPlayers) {
        this.otherPlayers = otherPlayers;
        initComboBox();
    }

    @SuppressWarnings("unchecked")
    public void initComboBox() {
        this.otherPlayerComboBoxModel = new DefaultComboBoxModel();
        for (Player player : this.otherPlayers) {
            this.otherPlayerComboBoxModel.addElement(player.getName());
        }
        this.jComboBoxOtherPlayers.setModel(this.otherPlayerComboBoxModel);
    }

    public String getSelectedPlayerName() {
        return (String) this.jComboBoxOtherPlayers.getSelectedItem();
    }

    @SuppressWarnings("unchecked")
    private void initJPanelSeries() {
        for (Series series : availableSeries) {
            JCheckBox jcb = new JCheckBox(series.getName());
            this.jCheckBoxes.add(jcb);
            this.jPanelSeries.add(jcb);
        }
        this.jPanelSeries.validate();
        this.validate();
        this.repaint();
    }

    public List<String> getSelectedSeries() {
        LinkedList<String> lst = new LinkedList<>();
        for (JCheckBox jCheckBox : this.jCheckBoxes) {
            if (jCheckBox.isSelected()) {
                lst.add(jCheckBox.getText());
            }
        }

        return lst;
    }

    private boolean validateRequest() {
        if (getSelectedSeries().size() != howManySeriesToPick()) {
            appendErrorMessage("Pick " + howManySeriesToPick() + " series.");
            return false;
        }

        if (!findSeriesInHand()) {
            appendErrorMessage("Include at least one series you have in you hand!");
            return false;
        }

        return true;
    }

    private boolean findSeriesInHand() {
        for (String string : getSelectedSeries()) {
            Series series = new Series(string);
            if (hand.isSeriesInHand(series)) {
                return true;
            }
        }

        return false;
    }

    private int howManySeriesToPick() {
        return this.hand.getCards().get(0).getSeries().size();
    }
}
