/*
 */
package swing.components;

import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Container;
import javax.swing.JFrame;
import swing.components.settings.JPanelSettingsMenu;

/**
 *
 * @author adamnark
 */
public class FrameGoFish extends JFrame {

    JPanelGoFish jPanelGoFish;
    
    /**
     * Creates new form GameFrame
     */
    public FrameGoFish() {
        initComponents();
        setLocationRelativeTo(null);
        
        Container contentPane = this.getContentPane();
        jPanelGoFish = new JPanelGoFish();
        contentPane.add(jPanelGoFish, BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Go Fish - Swing");
        setBackground(new java.awt.Color(255, 102, 51));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(600, 450));
        setMinimumSize(new java.awt.Dimension(600, 450));
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
