/*
 */
package swing.components;

/**
 *
 * @author adamnark
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form GameFrame
     */
    public MainFrame() {
        initComponents();
        setLocationRelativeTo(null);
        initListeners();

    }
    
    private void initListeners() {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        initGamePanel2 = new swing.components.init.initGamePanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Go Fish - Swing");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(600, 400));
        setMinimumSize(new java.awt.Dimension(600, 400));
        setPreferredSize(new java.awt.Dimension(600, 400));
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());
        getContentPane().add(initGamePanel2, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.components.init.initGamePanel initGamePanel2;
    // End of variables declaration//GEN-END:variables
}
