/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CardPanel.java
 *
 * Created on Dec 18, 2011, 7:36:59 PM
 */
package examples.splashscreen;

import examples.utils.ExamplesUtils;
import java.awt.CardLayout;

/**
 *
 * @author blecherl
 */
public class CardPanel extends javax.swing.JPanel {
    public static final String MAIN = "main";

    public static void main(String[] args) {
        ExamplesUtils.showExample("carLayout", new CardPanel());
    }

    /** Creates new form CardPanel */
    public CardPanel() {
        initComponents();
        this.add(new WelcomePanel(this), "splash");
        this.add(new MainUIPanel(), MAIN);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new CardLayout());
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    void switchToMainPanel() {
        CardLayout cardLayout = (CardLayout)getLayout();
        cardLayout.show(this, MAIN);
    }
}
