/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * WelcomePanel.java
 *
 * Created on Dec 18, 2011, 7:35:52 PM
 */
package examples.splashscreen;

import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.border.MatteBorder;

/**
 *
 * @author blecherl
 */
public class WelcomePanel extends javax.swing.JPanel {

    private CardPanel cardPanel;

    /** Creates new form WelcomePanel */
    public WelcomePanel() {
        initComponents();
        messagePanel.add(new JLabel("This is a welcome message"), BorderLayout.CENTER);
    }

    WelcomePanel(CardPanel cardPanel) {
        this();
        this.cardPanel = cardPanel;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomeButton = new JButton();
        messagePanel = new JPanel();

        welcomeButton.setText("Welcome");
        welcomeButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                welcomeButtonActionPerformed(evt);
            }
        });

        messagePanel.setBorder(new MatteBorder(null));
        messagePanel.setLayout(new BorderLayout());

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(262, Short.MAX_VALUE)
                .addComponent(welcomeButton)
                .addGap(217, 217, 217))
            .addComponent(messagePanel, GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(messagePanel, GroupLayout.PREFERRED_SIZE, 87, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
                .addComponent(welcomeButton)
                .addGap(149, 149, 149))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void welcomeButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_welcomeButtonActionPerformed
        cardPanel.switchToMainPanel();
    }//GEN-LAST:event_welcomeButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JPanel messagePanel;
    private JButton welcomeButton;
    // End of variables declaration//GEN-END:variables
}
