package example.swing.components.init.addplayer;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.SwingConstants;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author Iblecher
 */
public class AddPlayerPanel extends javax.swing.JPanel {

    public static final String PLAYER_ADD_EVENT = "playerAddEvent";

    /**
     * Creates new form PlayersManagerPanel
     */
    public AddPlayerPanel() {
	initComponents();
	initNameFieldChangeListener();
	initErrorMessageLabel();
	playerNameTextField.setText("Default Name");
    }

    public String getPlayerName(){
	return playerNameTextField.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new JLabel();
        playerNameTextField = new JTextField();
        addPlayerButton = new JButton();
        errorMessageLabel = new JLabel();

        jLabel1.setText("Player Name:");

        playerNameTextField.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                playerNameTextFieldActionPerformed(evt);
            }
        });

        addPlayerButton.setText("Add Player");
        addPlayerButton.setEnabled(false);
        addPlayerButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                addPlayerButtonActionPerformed(evt);
            }
        });

        errorMessageLabel.setFont(new Font("Tahoma", 1, 11)); // NOI18N
        errorMessageLabel.setForeground(new Color(255, 0, 0));
        errorMessageLabel.setHorizontalAlignment(SwingConstants.CENTER);

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(Alignment.LEADING)
                    .addComponent(errorMessageLabel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(playerNameTextField, GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE))
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(addPlayerButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(playerNameTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(addPlayerButton))
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(errorMessageLabel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addPlayerButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_addPlayerButtonActionPerformed
	fireAddPlayerEvent();
    }//GEN-LAST:event_addPlayerButtonActionPerformed

    private void playerNameTextFieldActionPerformed(ActionEvent evt) {//GEN-FIRST:event_playerNameTextFieldActionPerformed
        fireAddPlayerEvent();
    }//GEN-LAST:event_playerNameTextFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton addPlayerButton;
    private JLabel errorMessageLabel;
    private JLabel jLabel1;
    private JTextField playerNameTextField;
    // End of variables declaration//GEN-END:variables

    private void initNameFieldChangeListener() {
	playerNameTextField.getDocument().addDocumentListener(new DocumentListener() {
	    @Override
	    public void changedUpdate(DocumentEvent e) {
		enableAddPlayerButton();
	    }

	    @Override
	    public void removeUpdate(DocumentEvent e) {
		enableAddPlayerButton();
	    }

	    @Override
	    public void insertUpdate(DocumentEvent e) {
		enableAddPlayerButton();
	    }
	});
    }

    private void initErrorMessageLabel() {
	errorMessageLabel.setVisible(false);
    }
    
    private void enableAddPlayerButton(){
	addPlayerButton.setEnabled(!playerNameTextField.getText().isEmpty());
	hideErrorMessage();
    }

    public void showErrorMessage(String message) {
	errorMessageLabel.setText(message);
	errorMessageLabel.setVisible(true);
    }

    private void hideErrorMessage(){
	errorMessageLabel.setVisible(false);
    }

    public void clear(){
	hideErrorMessage();
	playerNameTextField.setText("");
    }

    private void fireAddPlayerEvent(){
	this.firePropertyChange(PLAYER_ADD_EVENT, true, false);
    }
}