/*
 */
package swing.components.init____old;

import java.awt.event.ActionListener;

/**
 *
 * @author adamnark
 */
public class PanelNewGame extends javax.swing.JPanel {

    /**
     * Creates new form initGamePanel
     */
    public PanelNewGame() {
        initComponents();        
    }

    public void addManualButtonAction(ActionListener al){
        this.buttonManual.addActionListener(al);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelNewGameButtons = new javax.swing.JPanel();
        buttonManual = new javax.swing.JButton();
        buttonReplay = new javax.swing.JButton();
        buttonQuit = new javax.swing.JButton();
        buttonXml = new javax.swing.JButton();
        panelTitle = new swing.components.init____old.panelTitle();

        setBackground(new java.awt.Color(204, 255, 255));
        setMaximumSize(new java.awt.Dimension(600, 400));
        setMinimumSize(new java.awt.Dimension(600, 400));
        setPreferredSize(new java.awt.Dimension(600, 400));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelNewGameButtons.setBackground(new java.awt.Color(255, 204, 204));
        panelNewGameButtons.setLayout(null);

        buttonManual.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonManual.setText("Manual");
        buttonManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonManualActionPerformed(evt);
            }
        });
        panelNewGameButtons.add(buttonManual);
        buttonManual.setBounds(350, 40, 230, 80);

        buttonReplay.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonReplay.setText("Play with last settings");
        buttonReplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonReplayActionPerformed(evt);
            }
        });
        panelNewGameButtons.add(buttonReplay);
        buttonReplay.setBounds(30, 240, 230, 80);

        buttonQuit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonQuit.setText("Quit");
        buttonQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonQuitActionPerformed(evt);
            }
        });
        panelNewGameButtons.add(buttonQuit);
        buttonQuit.setBounds(350, 240, 230, 80);

        buttonXml.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonXml.setText("XML");
        buttonXml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonXmlActionPerformed(evt);
            }
        });
        panelNewGameButtons.add(buttonXml);
        buttonXml.setBounds(30, 40, 230, 80);

        add(panelNewGameButtons, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 600, 350));

        panelTitle.setText("New Game");
        add(panelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void buttonManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonManualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonManualActionPerformed

    private void buttonReplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonReplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonReplayActionPerformed

    private void buttonQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonQuitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonQuitActionPerformed

    private void buttonXmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonXmlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonXmlActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonManual;
    private javax.swing.JButton buttonQuit;
    private javax.swing.JButton buttonReplay;
    private javax.swing.JButton buttonXml;
    private javax.swing.JPanel panelNewGameButtons;
    private swing.components.init____old.panelTitle panelTitle;
    // End of variables declaration//GEN-END:variables
}
