/*
 */
package swing.components.game.log;

/**
 *
 * @author adamnark
 */
public class JPanelLog extends javax.swing.JPanel {

    /**
     * Creates new form JPanelLog
     */
    public JPanelLog() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jTextPane1.setEditable(false);
        jTextPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextPane1.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextPane1.setFocusable(false);
        jTextPane1.setPreferredSize(new java.awt.Dimension(600, 50));
        jScrollPane1.setViewportView(jTextPane1);

        add(jScrollPane1);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables

    public void appendToLog(String string) {
        this.jTextPane1.setText(this.jTextPane1.getText() + "\r\n" + string);
    }
    public void setText(String string){
        this.jTextPane1.setText(string);
    }
}
