/*
 */
package swing.components.settings;

import java.awt.event.ActionListener;

/**
 *
 * @author adam
 */
public class JPanelMainMenu extends javax.swing.JPanel {

    public static final String EVENT_EXIT = "Exit Event";
    public static final String EVENT_GOTO_XML = "Event Go to XML";
    public static final String EVENT_GOTO_MANUAL = "Event Go to Manual";

    /**
     * Creates new form JPanelSettingsMenu
     */
    public JPanelMainMenu() {
        initComponents();
        setTitle();
    }

    private void setTitle() {
        this.jPanelTitle1.setTitle("New Game");
    }

    public void addButtonManualGameListener(ActionListener al) {
        this.jButtonManualGame.addActionListener(al);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTitle1 = new swing.utils.JPanelTitle();
        jButtonManualGame = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jButtonXMLGame = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(600, 450));
        setMinimumSize(new java.awt.Dimension(600, 450));
        setLayout(null);

        jPanelTitle1.setAlignmentX(0.0F);
        jPanelTitle1.setAlignmentY(0.0F);
        add(jPanelTitle1);
        jPanelTitle1.setBounds(0, 0, 600, 50);

        jButtonManualGame.setText("Manual Game");
        jButtonManualGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonManualGameActionPerformed(evt);
            }
        });
        add(jButtonManualGame);
        jButtonManualGame.setBounds(230, 80, 140, 60);

        jButtonExit.setText("Exit");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });
        add(jButtonExit);
        jButtonExit.setBounds(230, 340, 140, 60);

        jButtonXMLGame.setText("XML Game");
        jButtonXMLGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonXMLGameActionPerformed(evt);
            }
        });
        add(jButtonXMLGame);
        jButtonXMLGame.setBounds(230, 160, 140, 60);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(404, 230, 140, 25);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonManualGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManualGameActionPerformed
        this.firePropertyChange(EVENT_GOTO_MANUAL, false, true);
    }//GEN-LAST:event_jButtonManualGameActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        this.firePropertyChange(EVENT_EXIT, true, false);
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonXMLGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXMLGameActionPerformed
        this.firePropertyChange(EVENT_GOTO_XML, true, false);
    }//GEN-LAST:event_jButtonXMLGameActionPerformed

    public static final String EVENT_TEST = "event test test test";
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.firePropertyChange(EVENT_TEST, false, true);
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonManualGame;
    private javax.swing.JButton jButtonXMLGame;
    private swing.utils.JPanelTitle jPanelTitle1;
    // End of variables declaration//GEN-END:variables
}
