/*
 */
package swing.components.settings;

import java.awt.event.ActionListener;

/**
 *
 * @author adam
 */
public class JPanelSettingsMenu extends javax.swing.JPanel {

    public static final String EXIT_EVENT = "Exit Event";
    /**
     * Creates new form JPanelSettingsMenu
     */
    public JPanelSettingsMenu() {
        initComponents();
        setTitle();
    }
    
    private void setTitle() {
        this.jPanelTitle1.setTitle("New Game");
    }
    
    public void addButtonManualGameListener(ActionListener al){
        this.jButtonManualGame.addActionListener(al);
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTitle1 = new swing.utils.JPanelTitle();
        jButtonManualGame = new javax.swing.JButton();
        jButtonXMLGame = new javax.swing.JButton();
        jButtonXMLGame1 = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(600, 450));
        setMinimumSize(new java.awt.Dimension(600, 450));
        setLayout(null);

        jPanelTitle1.setAlignmentX(0.0F);
        jPanelTitle1.setAlignmentY(0.0F);
        add(jPanelTitle1);
        jPanelTitle1.setBounds(0, 0, 600, 50);

        jButtonManualGame.setText("Manual Game");
        jButtonManualGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonManualGameActionPerformed(evt);
            }
        });
        add(jButtonManualGame);
        jButtonManualGame.setBounds(230, 80, 140, 60);

        jButtonXMLGame.setText("Exit");
        jButtonXMLGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonXMLGameActionPerformed(evt);
            }
        });
        add(jButtonXMLGame);
        jButtonXMLGame.setBounds(230, 340, 140, 60);

        jButtonXMLGame1.setText("XML Game");
        jButtonXMLGame1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonXMLGame1ActionPerformed(evt);
            }
        });
        add(jButtonXMLGame1);
        jButtonXMLGame1.setBounds(230, 160, 140, 60);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonManualGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManualGameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonManualGameActionPerformed

    private void jButtonXMLGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXMLGameActionPerformed
        this.firePropertyChange(EXIT_EVENT, true, false);
    }//GEN-LAST:event_jButtonXMLGameActionPerformed

    private void jButtonXMLGame1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXMLGame1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonXMLGame1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonManualGame;
    private javax.swing.JButton jButtonXMLGame;
    private javax.swing.JButton jButtonXMLGame1;
    private swing.utils.JPanelTitle jPanelTitle1;
    // End of variables declaration//GEN-END:variables
}
