/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package swing.components.game.play.playarea;

/**
 *
 * @author Natalie
 */
public class JPanelActions extends javax.swing.JPanel {

    public static final String EVENT_REQUEST = "JPanelActions - request";
    public static final String EVENT_THROW = "JPanelActions - throw";
    public static final String EVENT_SKIP = "JPanelActions - skip";

    /**
     * Creates new form JPanelActions
     */
    public JPanelActions() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonRequest = new javax.swing.JButton();
        jButtonThrow = new javax.swing.JButton();
        jButtonSkip = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("What do you want to do?"));

        jButtonRequest.setText("Request");
        jButtonRequest.setToolTipText("Request a card");
        jButtonRequest.setPreferredSize(new java.awt.Dimension(100, 70));
        jButtonRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRequestActionPerformed(evt);
            }
        });
        add(jButtonRequest);

        jButtonThrow.setText("Throw");
        jButtonThrow.setToolTipText("Throw selected cards");
        jButtonThrow.setPreferredSize(new java.awt.Dimension(100, 70));
        jButtonThrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThrowActionPerformed(evt);
            }
        });
        add(jButtonThrow);

        jButtonSkip.setText("Skip");
        jButtonSkip.setToolTipText("Skip the rest of your turn");
        jButtonSkip.setPreferredSize(new java.awt.Dimension(100, 70));
        jButtonSkip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSkipActionPerformed(evt);
            }
        });
        add(jButtonSkip);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRequestActionPerformed
        this.firePropertyChange(EVENT_REQUEST, false, true);
    }//GEN-LAST:event_jButtonRequestActionPerformed

    private void jButtonThrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThrowActionPerformed
        this.firePropertyChange(EVENT_THROW, false, true);
    }//GEN-LAST:event_jButtonThrowActionPerformed

    private void jButtonSkipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSkipActionPerformed
        this.firePropertyChange(EVENT_SKIP, false, true);
    }//GEN-LAST:event_jButtonSkipActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRequest;
    private javax.swing.JButton jButtonSkip;
    private javax.swing.JButton jButtonThrow;
    // End of variables declaration//GEN-END:variables
}
