/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package swing.components.game.play.playarea;

/**
 *
 * @author Natalie
 */
public class JPanelPlayAreaComputer extends javax.swing.JPanel {

    /**
     * Creates new form JPanelComputerPlayArea
     */
    public JPanelPlayAreaComputer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonPlay = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Computer player's turn"));
        setLayout(new java.awt.BorderLayout());

        jButtonPlay.setText("Play");
        add(jButtonPlay, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPlay;
    // End of variables declaration//GEN-END:variables

    public void setPlayerName(String name) {
        setBorder(javax.swing.BorderFactory.createTitledBorder(name + "'s turn"));
    }
}
