/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package swing.components.game.play.playarea;

import swing.components.game.play.JPanelHand;

/**
 *
 * @author Natalie
 */
public class JPanelPlayAreaHuman extends javax.swing.JPanel {

    /**
     * Creates new form JPanelPlayArea
     */
    public JPanelPlayAreaHuman() {
        initComponents();
    }
    
    public JPanelHand getJPanelHand(){
        return jPanelHand2;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelActions2 = new swing.components.game.play.JPanelActions();
        jPanelHand2 = new swing.components.game.play.JPanelHand();

        setLayout(new java.awt.BorderLayout());
        add(jPanelActions2, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout jPanelHand2Layout = new javax.swing.GroupLayout(jPanelHand2);
        jPanelHand2.setLayout(jPanelHand2Layout);
        jPanelHand2Layout.setHorizontalGroup(
            jPanelHand2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 413, Short.MAX_VALUE)
        );
        jPanelHand2Layout.setVerticalGroup(
            jPanelHand2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 174, Short.MAX_VALUE)
        );

        add(jPanelHand2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.components.game.play.JPanelActions jPanelActions2;
    private swing.components.game.play.JPanelHand jPanelHand2;
    // End of variables declaration//GEN-END:variables
}
