/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DharmaSationPanel.java
 *
 * Created on Mar 20, 2011, 11:18:45 AM
 */

package examples.LostExample.others.stations;

import examples.utils.ExamplesUtils;

import javax.swing.*;

/**
 *
 * @author blecherl
 */
public class DharmaStationPanel extends javax.swing.JPanel {

    /** Creates new form DharmaStationPanel */
    public DharmaStationPanel(DharmaStation dharmaStation) {
        initComponents();
        title.setText(dharmaStation.getTitle());
        stationImage.setIcon(ExamplesUtils.getImageIcon(dharmaStation.getImageName()));
//        stationImage.setPreferredSize(new Dimension(200, 400));

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        stationImage = new javax.swing.JLabel();
        othersPanel = new javax.swing.JPanel();

        setName("Form"); // NOI18N
        setLayout(new java.awt.BorderLayout());

        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setBorder(new javax.swing.border.MatteBorder(null));
        title.setName("title"); // NOI18N
        add(title, java.awt.BorderLayout.PAGE_START);

        stationImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stationImage.setName("stationImage"); // NOI18N
        add(new JScrollPane (stationImage), java.awt.BorderLayout.CENTER);

        othersPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        othersPanel.setName("othersPanel"); // NOI18N
        othersPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        add(othersPanel, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel othersPanel;
    private javax.swing.JLabel stationImage;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables

}
